"""Initial migration

Revision ID: 6320a99502e1
Revises: 
Create Date: 2026-04-17 07:22:12.684803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6320a99502e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(username) >= 3', name='ck_username_len'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('medias',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.Enum('FILME', 'SERIE', 'ANIME', 'DORAMA', 'LIVRO', 'REALITY', name='mediatype'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('classification', sa.Enum('POSITIVO', 'NEUTRO', 'NEGATIVO', name='classification'), nullable=False),
    sa.Column('mood_before', sa.SmallInteger(), nullable=False),
    sa.Column('mood_after', sa.SmallInteger(), nullable=False),
    sa.Column('primary_emotion', sa.Enum('FELIZ', 'TRISTE', 'ANSIOSO', 'MOTIVADO', 'ENTEDIADO', 'NEUTRO', name='emotion'), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta_mood', sa.SmallInteger(), nullable=False),
    sa.Column('time_efficiency', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('duration_min > 0 AND duration_min <= 10000', name='ck_duration_bounds'),
    sa.CheckConstraint('mood_after >= 0 AND mood_after <= 10', name='ck_mood_after_bounds'),
    sa.CheckConstraint('mood_before >= 0 AND mood_before <= 10', name='ck_mood_before_bounds'),
    sa.CheckConstraint('rating >= 0 AND rating <= 10', name='ck_rating_bounds'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.create_index('ix_media_user_date', ['user_id', 'watched_at'], unique=False)
        batch_op.create_index('ix_media_user_type', ['user_id', 'media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_medias_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_medias_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_medias_primary_emotion'), ['primary_emotion'], unique=False)
        batch_op.create_index(batch_op.f('ix_medias_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medias_watched_at'), ['watched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medias_watched_at'))
        batch_op.drop_index(batch_op.f('ix_medias_user_id'))
        batch_op.drop_index(batch_op.f('ix_medias_primary_emotion'))
        batch_op.drop_index(batch_op.f('ix_medias_media_type'))
        batch_op.drop_index(batch_op.f('ix_medias_classification'))
        batch_op.drop_index('ix_media_user_type')
        batch_op.drop_index('ix_media_user_date')

    op.drop_table('medias')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
